version: "3.8"

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    image: nginx:42
    container_name: nginx
    build:
      context: requirements/nginx
      args:
        - LOGIN
    # environment:
    #   - DOMAIN_NAME
    #   - NGINX_CERT_PATH
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always

  mariadb:
    image: mariadb:42
    container_name: mariadb
    build: requirements/mariadb
    environment:
      - WP_DB_NAME
      - WP_DB_USER
      - WP_DB_PASSWORD
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress:42
    container_name: wordpress
    build: requirements/wordpress
    environment:
      - DOMAIN_NAME
      - WP_DB_NAME
      - WP_DB_USER
      - WP_DB_PASSWORD
      - WP_DB_EMAIL
      - WP_GUEST_USER
      - WP_GUEST_PASSWORD
      - WP_GUEST_EMAIL
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: always