FROM debian:bullseye

RUN apt-get update -y && \
        apt-get upgrade -y && \
        apt-get install -y mariadb-server

RUN echo "[mysqld] \n\
    skip-networking=0 \n\
    skip-bind-address" >> /etc/mysql/my.cnf

COPY tools/* /usr/bin/

RUN chmod +x /usr/bin/mariadb_setup.sh

RUN service mariadb start && /usr/bin/mariadb_setup.sh

CMD ["mysqld_safe"]