#!/usr/bin/env bash

mariadb -u root -p"$WP_DB_PASSWORD" << EOF
CREATE DATABASE IF NOT EXISTS $WP_DB_NAME;
CREATE USER '$WP_DB_USER'@'%' IDENTIFIED BY '$WP_DB_PASSWORD';
GRANT ALL ON $WP_DB_NAME.* TO '$WP_DB_USER'@'%';
FLUSH PRIVILEGES;
EOF